"""commons spine: postgis + site / site_source / site_conflict / user_note

The initial migration (T015) for the storage mapping in
``specs/001-research-cited-sites/data-model.md`` §4 / tech-design §2. It is written by
hand rather than autogenerated so the PostGIS extension, the GiST index on ``site.geom``
and the append-only intent of ``site_source`` are explicit and reviewable.

Two deliberate asymmetries between ``upgrade`` and ``downgrade``:

1. ``CREATE EXTENSION IF NOT EXISTS postgis`` is **not** mirrored by a ``DROP EXTENSION``.
   The extension is shared database infrastructure (Cloud SQL may pre-install it, other
   schemas may depend on it); dropping it on downgrade would be destructive far outside
   this migration's blast radius.
2. Indexes are dropped explicitly before their tables — Postgres would drop them with the
   table anyway, but naming them keeps the reversal auditable.

Revision ID: 0001_commons_spine
Revises:
Create Date: 2026-08-01

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_commons_spine"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SRID = 4326


def upgrade() -> None:
    """Create the PostGIS extension and the four commons tables."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "site",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("gers_id", sa.Text(), nullable=True),
        sa.Column(
            "geom",
            # spatial_index=False: the GiST index is created explicitly below.
            geoalchemy2.Geometry(geometry_type="POINT", srid=SRID, spatial_index=False),
            nullable=False,
        ),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site")),
    )
    op.create_index(op.f("ix_site_gers_id"), "site", ["gers_id"])
    # The coverage query (`ST_Within(geom, :area_polygon)`) lives or dies by this index.
    op.create_index("ix_site_geom", "site", ["geom"], postgresql_using="gist")

    # Append-only provenance. The FK is plain NO ACTION on purpose: the database refuses
    # to delete a site while its audit trail still references it (data-model §4).
    op.create_table(
        "site_source",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], name=op.f("fk_site_source_site_id_site")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_source")),
    )
    op.create_index(op.f("ix_site_source_site_id"), "site_source", ["site_id"])

    op.create_table(
        "site_conflict",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], name=op.f("fk_site_conflict_site_id_site")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site_conflict")),
    )
    op.create_index(op.f("ix_site_conflict_site_id"), "site_conflict", ["site_id"])

    # Private, row-scoped to user_id — never joined into a commons read (FR-010).
    op.create_table(
        "user_note",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], name=op.f("fk_user_note_site_id_site")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_note")),
    )
    op.create_index("ix_user_note_user_id_site_id", "user_note", ["user_id", "site_id"])


def downgrade() -> None:
    """Drop the four tables (the PostGIS extension is left alone — see module docstring)."""
    op.drop_index("ix_user_note_user_id_site_id", table_name="user_note")
    op.drop_table("user_note")
    op.drop_index(op.f("ix_site_conflict_site_id"), table_name="site_conflict")
    op.drop_table("site_conflict")
    op.drop_index(op.f("ix_site_source_site_id"), table_name="site_source")
    op.drop_table("site_source")
    op.drop_index("ix_site_geom", table_name="site")
    op.drop_index(op.f("ix_site_gers_id"), table_name="site")
    op.drop_table("site")
